### ISSUE TITLE
Organize by author?

### ISSUE THREAD

**Issue by naturecodevoid** [RLBot/RLBotPack#1]
Hi. I was looking at the bots, and I saw RLMarvin's bots in one folder, but all the other bots in separate folders. I think you might want to organize the bots one way or another, because if there are a lot of bots, it could get pretty confusing for new comers.

I have come up with two organization ways.

1: By author. Kind of like RLMarvin's bots, but everyone has a folder. Like instead of `RLBotPack/Cartana`, it would be (please correct me if I'm incorrect, don't know the community very well) `RLBotPack/Martmists/Cartana`.

2: By bots, and no author grouping. This would mean that RLMarvin's folder would be split into rashBot, stick, etc.

If you can, I would appreciate feedback on this idea. **I am more than happy to work on either idea.**

Thanks.

**Comment by dtracers** [comment]
I believe the only bot that would be combined by author would be snek and beast.  Every other bot is by a different author already so it would really be just renaming the folders.

The reason why Marvin bots are that way was that Marvin has a repo with his bots organized in that fashion.   Marvin has not been active so we can not really find out a different name or organization for those bots.   I think that organization for the botpack is a great idea I am not sure that solution works.  Especially because the purpose of this is to get used in a GUI where the ordering is very distinct from what is in this repo

**Comment by DomNomNom** [comment]
I don't have much of an opinion on the folder structure.
Searching / ordering by author might be a valuable feature in the GUI.

Another thing to consider: Provide an official way of accessing named bot configs. For instance, when someone wants to create a MatchConfig for a TrainingExercise against a particular bot of the botpack, they shouldn't have to go hunting through subfolders and shouldn't have to make assumptions about where the BotPack is stored.

**Comment by naturecodevoid** [comment]
Ok. Sorry I was so late to repsond. I might close this issue, but DomNomNom has good ideas, and also dtracers
