### ISSUE TITLE
invisibot ain't feeling so hot

### ISSUE THREAD

**Issue by Impossibum** [RLBot/RLBotPack#250]
@azeemba I'm being told Invisibot is no longer functioning. This is likely a result of kamael family switching over to a venv to tackle numba issues many people were experiencing with the final build. All I can say is that at least I waited until the final update to explode things ;p

**Comment by azeemba** [comment]
I just did a fresh install of RLBotGUI and downloaded the botpack. Invisibot seems to be working fine. I also played with Kamael and then tried Invisibot again and that didn't cause any issues either.

Since Invisibot has its own copy of Kamael, I think changes in Kamael shouldn't impact Invisibot.

Do we have any specific information in what kind of issues people are seeing? or perhaps there are error messages?

**Comment by Impossibum** [comment]
My apologies on that front, I didn't test myself and just forwarded information from someone who said they were having issues. Virx had already taken care of it apparently.

> I just did a fresh install of RLBotGUI and downloaded the botpack. Invisibot seems to be working fine. I also played with Kamael and then tried Invisibot again and that didn't cause any issues either.
> 
> Since Invisibot has its own copy of Kamael, I think changes in Kamael shouldn't impact Invisibot.
> 
> Do we have any specific information in what kind of issues people are seeing? or perhaps there are error messages?

**Comment by Impossibum** [comment]
his name is JT Duczi in discord. We all should shame him mercilessly! ;p
